# Generated by Django 3.1.4 on 2020-12-12 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=120)),
                ('description', models.TextField(default='', max_length=500)),
                ('priority', models.CharField(default='low', max_length=120)),
                ('status', models.CharField(default='backlog', max_length=120)),
                ('is_completed', models.BooleanField(default=False)),
            ],
        ),
    ]
